clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/prox/BTC.py &
python3 /home/ubuntu/Desktop/prox/ETH.py &
python3 /home/ubuntu/Desktop/prox/BNB.py &
python3 /home/ubuntu/Desktop/prox/XRP.py &
python3 /home/ubuntu/Desktop/prox/ADA.py &
python3 /home/ubuntu/Desktop/prox/SOL.py &
python3 /home/ubuntu/Desktop/prox/DOGE.py &
python3 /home/ubuntu/Desktop/prox/MATIC.py &
python3 /home/ubuntu/Desktop/prox/DOT.py &
python3 /home/ubuntu/Desktop/prox/DAI.py &
python3 /home/ubuntu/Desktop/prox/SHIB.py &
python3 /home/ubuntu/Desktop/prox/TRX.py &
python3 /home/ubuntu/Desktop/prox/AVAX.py &
python3 /home/ubuntu/Desktop/prox/UNI.py &
python3 /home/ubuntu/Desktop/prox/WBTC.py &
python3 /home/ubuntu/Desktop/prox/LEO.py &
python3 /home/ubuntu/Desktop/prox/LTC.py &
python3 /home/ubuntu/Desktop/prox/ATOM.py &
python3 /home/ubuntu/Desktop/prox/LINK.py &
python3 /home/ubuntu/Desktop/prox/ETC.py &
python3 /home/ubuntu/Desktop/prox/XLM.py &
python3 /home/ubuntu/Desktop/prox/FTT.py &
python3 /home/ubuntu/Desktop/prox/NEAR.py &
python3 /home/ubuntu/Desktop/prox/CRO.py &
python3 /home/ubuntu/Desktop/prox/XMR.py &
python3 /home/ubuntu/Desktop/prox/ALGO.py &
python3 /home/ubuntu/Desktop/prox/BCH.py &
python3 /home/ubuntu/Desktop/prox/LUNC.py &
python3 /home/ubuntu/Desktop/prox/QNT.py &
python3 /home/ubuntu/Desktop/prox/FLOW.py &
python3 /home/ubuntu/Desktop/prox/VET.py &
python3 /home/ubuntu/Desktop/prox/TON.py &
python3 /home/ubuntu/Desktop/prox/APE.py &
python3 /home/ubuntu/Desktop/prox/FIL.py &
python3 /home/ubuntu/Desktop/prox/ICP.py &
python3 /home/ubuntu/Desktop/prox/HBAR.py &
python3 /home/ubuntu/Desktop/prox/EGLD.py &
python3 /home/ubuntu/Desktop/prox/XTZ.py &
python3 /home/ubuntu/Desktop/prox/MANA.py &
python3 /home/ubuntu/Desktop/prox/SAND.py &
python3 /home/ubuntu/Desktop/prox/CHZ.py &
python3 /home/ubuntu/Desktop/prox/EOS.py &
python3 /home/ubuntu/Desktop/prox/AAVE.py &
python3 /home/ubuntu/Desktop/prox/THETA.py &
python3 /home/ubuntu/Desktop/prox/AXS.py &
python3 /home/ubuntu/Desktop/prox/USDP.py &
python3 /home/ubuntu/Desktop/prox/OKB.py &
python3 /home/ubuntu/Desktop/prox/BSV.py &
python3 /home/ubuntu/Desktop/prox/TUSD.py &
python3 /home/ubuntu/Desktop/prox/MKR.py &
python3 /home/ubuntu/Desktop/prox/KCS.py &
python3 /home/ubuntu/Desktop/prox/ZEC.py &
python3 /home/ubuntu/Desktop/prox/USDD.py &
python3 /home/ubuntu/Desktop/prox/HT.py &
python3 /home/ubuntu/Desktop/prox/XEC.py &
python3 /home/ubuntu/Desktop/prox/MIOTA.py &
python3 /home/ubuntu/Desktop/prox/BTT.py &
python3 /home/ubuntu/Desktop/prox/USDN.py &
python3 /home/ubuntu/Desktop/prox/CAKE.py &
python3 /home/ubuntu/Desktop/prox/GRT.py &
python3 /home/ubuntu/Desktop/prox/NEO.py &
python3 /home/ubuntu/Desktop/prox/HNT.py &
python3 /home/ubuntu/Desktop/prox/KLAY.py &
python3 /home/ubuntu/Desktop/prox/FTM.py &
python3 /home/ubuntu/Desktop/prox/PAXG.py &
python3 /home/ubuntu/Desktop/prox/SNX.py &
python3 /home/ubuntu/Desktop/prox/RUNE.py &
python3 /home/ubuntu/Desktop/prox/NEXO.py &
python3 /home/ubuntu/Desktop/prox/GT.py &
python3 /home/ubuntu/Desktop/prox/DASH.py &
python3 /home/ubuntu/Desktop/prox/CRV.py &
python3 /home/ubuntu/Desktop/prox/BAT.py &
python3 /home/ubuntu/Desktop/prox/ENJ.py &
python3 /home/ubuntu/Desktop/prox/LDO.py &
python3 /home/ubuntu/Desktop/prox/STX.py &
python3 /home/ubuntu/Desktop/prox/KAVA.py &
python3 /home/ubuntu/Desktop/prox/COMP.py &
python3 /home/ubuntu/Desktop/prox/ZIL.py &
python3 /home/ubuntu/Desktop/prox/FEI.py &
python3 /home/ubuntu/Desktop/prox/RVN.py &
python3 /home/ubuntu/Desktop/prox/MINA.py &
python3 /home/ubuntu/Desktop/prox/WAVES.py &
python3 /home/ubuntu/Desktop/prox/XDC.py &
python3 /home/ubuntu/Desktop/prox/USDTC.py &
python3 /home/ubuntu/Desktop/prox/GMT.py &
python3 /home/ubuntu/Desktop/prox/TWT.py &
python3 /home/ubuntu/Desktop/prox/LRC.py &
python3 /home/ubuntu/Desktop/prox/DCR.py &
python3 /home/ubuntu/Desktop/prox/CVX.py &
python3 /home/ubuntu/Desktop/prox/CSPR.py &
python3 /home/ubuntu/Desktop/prox/XEM.py &
python3 /home/ubuntu/Desktop/prox/KSM.py &
python3 /home/ubuntu/Desktop/prox/CELO.py &
python3 /home/ubuntu/Desktop/prox/BTG.py &
python3 /home/ubuntu/Desktop/prox/ENS.py &
python3 /home/ubuntu/Desktop/prox/1INCH.py &
python3 /home/ubuntu/Desktop/prox/HOT.py &
python3 /home/ubuntu/Desktop/prox/LUNA.py &
python3 /home/ubuntu/Desktop/prox/RSR.py &
python3 /home/ubuntu/Desktop/prox/BNX.py &
python3 /home/ubuntu/Desktop/prox/GUSD.py &
python3 /home/ubuntu/Desktop/prox/ROSE.py &
python3 /home/ubuntu/Desktop/prox/YFI.py &
python3 /home/ubuntu/Desktop/prox/QTUM.py &
python3 /home/ubuntu/Desktop/prox/AR.py &
python3 /home/ubuntu/Desktop/prox/ANKR.py &
python3 /home/ubuntu/Desktop/prox/GNO.py &
python3 /home/ubuntu/Desktop/prox/GALA.py &
python3 /home/ubuntu/Desktop/prox/TFUEL.py &
python3 /home/ubuntu/Desktop/prox/KDA.py &
python3 /home/ubuntu/Desktop/prox/IOTX.py &
python3 /home/ubuntu/Desktop/prox/GLM.py &
python3 /home/ubuntu/Desktop/prox/BTRST.py &
python3 /home/ubuntu/Desktop/prox/JST.py &
python3 /home/ubuntu/Desktop/prox/CEL.py &
python3 /home/ubuntu/Desktop/prox/POLY.py &
python3 /home/ubuntu/Desktop/prox/ONE.py &
python3 /home/ubuntu/Desktop/prox/HIVE.py &
python3 /home/ubuntu/Desktop/prox/OMG.py &
python3 /home/ubuntu/Desktop/prox/LPT.py &
python3 /home/ubuntu/Desktop/prox/ZRX.py &
python3 /home/ubuntu/Desktop/prox/BAL.py &
python3 /home/ubuntu/Desktop/prox/FLUX.py &
python3 /home/ubuntu/Desktop/prox/IOST.py &
python3 /home/ubuntu/Desktop/prox/ICX.py &
python3 /home/ubuntu/Desktop/prox/BORA.py &
python3 /home/ubuntu/Desktop/prox/AMP.py &
python3 /home/ubuntu/Desktop/prox/XYM.py &
python3 /home/ubuntu/Desktop/prox/SRM.py &
python3 /home/ubuntu/Desktop/prox/KNC.py &
python3 /home/ubuntu/Desktop/prox/ONT.py &
python3 /home/ubuntu/Desktop/prox/OP.py &
python3 /home/ubuntu/Desktop/prox/GLMR.py &
python3 /home/ubuntu/Desktop/prox/CHSB.py &
python3 /home/ubuntu/Desktop/prox/STORJ.py &
python3 /home/ubuntu/Desktop/prox/WAXP.py &
python3 /home/ubuntu/Desktop/prox/SC.py &
python3 /home/ubuntu/Desktop/prox/WOO.py &
python3 /home/ubuntu/Desktop/prox/ZEN.py &
python3 /home/ubuntu/Desktop/prox/XCH.py &
python3 /home/ubuntu/Desktop/prox/SXP.py &
python3 /home/ubuntu/Desktop/prox/SUSHI.py &
python3 /home/ubuntu/Desktop/prox/IMX.py &
python3 /home/ubuntu/Desktop/prox/MXC.py &
python3 /home/ubuntu/Desktop/prox/AUDIO.py &
python3 /home/ubuntu/Desktop/prox/NFT.py &
python3 /home/ubuntu/Desktop/prox/UMA.py &
python3 /home/ubuntu/Desktop/prox/PLA.py &
python3 /home/ubuntu/Desktop/prox/SKL.py &
python3 /home/ubuntu/Desktop/prox/ABBC.py &
python3 /home/ubuntu/Desktop/prox/SCRT.py &
python3 /home/ubuntu/Desktop/prox/SLP.py &
python3 /home/ubuntu/Desktop/prox/DGB.py &
python3 /home/ubuntu/Desktop/prox/ELON.py &
python3 /home/ubuntu/Desktop/prox/INJ.py &
python3 /home/ubuntu/Desktop/prox/VGX.py &
python3 /home/ubuntu/Desktop/prox/CKB.py &
python3 /home/ubuntu/Desktop/prox/CVC.py &
python3 /home/ubuntu/Desktop/prox/LSK.py &
python3 /home/ubuntu/Desktop/prox/VLX.py &
python3 /home/ubuntu/Desktop/prox/PUNDIX.py &
python3 /home/ubuntu/Desktop/prox/COTI.py &
python3 /home/ubuntu/Desktop/prox/KEEP.py &
python3 /home/ubuntu/Desktop/prox/DAO.py &
python3 /home/ubuntu/Desktop/prox/REN.py &
python3 /home/ubuntu/Desktop/prox/MED.py &
python3 /home/ubuntu/Desktop/prox/RNDR.py &
python3 /home/ubuntu/Desktop/prox/CEEK.py &
python3 /home/ubuntu/Desktop/prox/REEF.py &
python3 /home/ubuntu/Desktop/prox/EWT.py &
python3 /home/ubuntu/Desktop/prox/PEOPLE.py &
python3 /home/ubuntu/Desktop/prox/BTCST.py &
python3 /home/ubuntu/Desktop/prox/WIN.py &
python3 /home/ubuntu/Desktop/prox/NU.py &
python3 /home/ubuntu/Desktop/prox/CELR.py &
python3 /home/ubuntu/Desktop/prox/SYS.py &
python3 /home/ubuntu/Desktop/prox/ONG.py &
python3 /home/ubuntu/Desktop/prox/XNO.py &
python3 /home/ubuntu/Desktop/prox/REQ.py &
python3 /home/ubuntu/Desktop/prox/DAG.py &
python3 /home/ubuntu/Desktop/prox/ORBS.py &
python3 /home/ubuntu/Desktop/prox/SPELL.py &
python3 /home/ubuntu/Desktop/prox/RLC.py &
python3 /home/ubuntu/Desktop/prox/OCEAN.py &
python3 /home/ubuntu/Desktop/prox/API3.py &
python3 /home/ubuntu/Desktop/prox/SNT.py &
python3 /home/ubuntu/Desktop/prox/TRIBE.py &
python3 /home/ubuntu/Desktop/prox/ARDR.py &
python3 /home/ubuntu/Desktop/prox/PYR.py &
python3 /home/ubuntu/Desktop/prox/FX.py &
python3 /home/ubuntu/Desktop/prox/UOS.py &
python3 /home/ubuntu/Desktop/prox/POWER.py &
python3 /home/ubuntu/Desktop/prox/ACA.py &
python3 /home/ubuntu/Desktop/prox/PROM.py &
python3 /home/ubuntu/Desktop/prox/DENT.py &
python3 /home/ubuntu/Desktop/prox/CHR.py &
python3 /home/ubuntu/Desktop/prox/MX.py &
python3 /home/ubuntu/Desktop/prox/%launcher%


